# Generated by Django 6.0.3 on 2026-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedCSVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file_name', models.CharField(max_length=255)),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'uploads_processedcsvrecord',
                'indexes': [models.Index(fields=['source_file_name', 'row_number'], name='uploads_pro_source__a08145_idx'), models.Index(fields=['created_at'], name='uploads_pro_created_a4e3f1_idx')],
                'unique_together': {('source_file_name', 'row_number')},
            },
        ),
    ]
