# Generated by Django 6.0.3 on 2026-03-30 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('record_date', models.DateField(db_index=True)),
                ('payload', models.JSONField(blank=True, null=True)),
                ('source_file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('source_row_number', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'search_datarecord',
                'ordering': ['-record_date', '-created_at'],
                'indexes': [models.Index(fields=['category', 'record_date'], name='search_data_categor_5c98a9_idx')],
            },
        ),
    ]
